library(tidyverse)
library(readxl)


# 2026-01-22 ----

ncos_ebird_2026_01_22 <- read_xlsx("data/excel_summaries/2026/NCOS_Bird_Survey_Data_2026_01_22.xlsx")[-1, ]

# the key columns are the first one (bird species) and the last one (grand total)
# those will become "Common Name" and "Number" in the reformatted data.


# 1. Create a data frame matching eBird Record Format (ERF)
# Full list of eBird Record Format Columns: 
# Common Name, Genus, Species, Number, Species Comments, 
# Date, Start Time, State/Province, Country, Location, 
# Distance, Area, Duration, Observation Type, Checklist Comments

# Common Name and Number will be in the Excel Summary Sheet (generated by a pivot table, sometimes the tab is called TOTALS)

# Genus and Species can be left blank, because eBird will match those to the common name

# Species comments will be blank

# Date should be the same for the entire survey

# Start Time will be in the raw data tab of the Excel, in the "Starting Time" column (in H:MM format)

# Location will always be the same: UCSB North Campus Open Space (formerly Ocean Meadows Golf Course)

# State/Province: CA

# Country: US

#Latitude & Longitude will always stay the same: 34.42	-119.877







# 



# 2. Export as CSV without headers
#  this is practice
# this is a conflict 
# this is probably going to create a merge conflict!

