---
title: "MV_work_2026-01-18"
output: html_document
---

```{r setup,include = F}

library(here)
library(tidyverse)
library(popbayes)
library(R2jags)

datapath <- here("data","aggregated","MV_updated_aggregated.rds")
data <- readRDS(datapath)

```

# test

```{r hierarchical model parameter estimation}

test <- system.file("extdata", "garamba_survey.csv", 
                         package = "popbayes")
test_data <- read.csv(file = test)

test_format <- format_data(test_data,path = path,field_method = "field_method",
  pref_field_method = "pref_field_method",
  conversion_A2G    = "conversion_A2G",
  rmax              = "rmax")

a_buselaphus <- filter_series(test_format, 
                                        location = "Garamba",
                                        species  = "Alcelaphus buselaphus")

a_buselaphus_mod <- fit_trend(a_buselaphus, path = path)

plot_trend(series = "garamba__alcelaphus_buselaphus", 
                     path   = path)

a_buselaphus_mod[["garamba__alcelaphus_buselaphus"]][["BUGSoutput"]][["sims.list"]][["r"]]

```

# fitting model to bird survey data

```{r gotelli hierarchical model r parameter estimation}

path <- here("code","from_Matt_Vinh","MV_gotelli_bootstrapping_hierarchical_model")

data <- data %>% mutate(location = rep("NCOS",times = nrow(data)),
                        stat_method = rep("T",times = nrow(data)),
                        include = case_when(
                          grepl("sp.",species) ~ "no",
                          grepl("hybrid",species) ~ "no",
                          .default = "yes"),
                        rmax = rep(0.01,times = nrow(data)))

species_list <- c("Black-chinned Hummingbird","Black-headed Grosbeak","Blue Grosbeak","Brewer's Blackbird","California Quail","Canvasback","Chipping Sparrow","Clay-colored Sparrow","Common Raven","Fox Sparrow","Mute Swan","Pectoral Sandpiper","Sanderling","Solitary Sandpiper","Vaux's Swift","Western Wood-Pewee","Whimbrel","Willet","Willow Flycatcher")

mod <- data %>% filter(include == "yes",!species %in% species_list)

formatted <- format_data(mod,
                         path = path,
                         date = "year",
                         lower_ci = NULL,
                         upper_ci = NULL,
                         rmax = "rmax")

trend <- fit_trend(formatted,
                   path = path,
                   model_opts = list(100,T),
                   mcmc_opts = list(ni = 4200,nt = 5,nb = 1000,nc = 5))

#Error in update.jags(model, n.iter, ...) : Error in node sdr
#Invalid parent values

```

