---
title: "MV_2025-09-06"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup,warning = F}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)

# establishing ncos bird surveys .csv filepath using here package
# removing unnecessary variables
birdsurveyfilepath <- here("data","aggregated","dryad_2017-2023","doi_10_5061_dryad_bvq83bkhz__v20240617","NCOS_Monthly_Bird_Surveys_2017-2023.csv")
birdsurveys <- read_csv(birdsurveyfilepath)
birdsurveys_filtered <- birdsurveys %>%
  select(-c(Repeat.Observation:Slough.Water.Elevation..ft.)) %>% 
  filter(Substrate != "<Null>" & !is.na(Count))
birdsurveys_filtered$Substrate[birdsurveys_filtered$Substrate == "rocks"] <- "Rock"
birdsurveys_filtered$Substrate[birdsurveys_filtered$Substrate == 
                                 "Other (Enter in Observation Notes)"] <- "Other"

# establishing aos checklist nacc species list .csv using here package
# removing unnecessary variables
naccfilepath <- here("data","aos_checklist","NACC_list_species_2024_65th.csv")
nacc <- read_csv(naccfilepath)
nacc_filtered <- nacc %>% select(-c(french_name,annotation:status_misplaced))

# creating date variable with correct data type with lubridate package (tidyverse)
# removing NA dates
birdsurveys_filtered$obs_date2 <- substr(birdsurveys_filtered$Observation.Date,1,10)
birdsurveys_filtered <- birdsurveys_filtered %>% 
  mutate(obs_date3 = parse_date_time(obs_date2,orders = c("mdy","ymd"))) %>% 
  filter(!is.na(obs_date3))

# creating variable for survey year as opposed to calendar year
date_borders <- ymd(c("2017-09-01","2018-09-01","2019-09-01","2020-09-01","2021-09-01",
                      "2022-09-01","2023-09-01","2024-09-01"))
survey_years <- c("2017-2018","2018-2019","2019-2020","2020-2021","2021-2022","2022-2023")
for (i in 1:nrow(birdsurveys_filtered)){
  for (j in 1:length(unique(birdsurveys_filtered$Year))){
    if (birdsurveys_filtered$obs_date3[i] >= date_borders[j] & 
       birdsurveys_filtered$obs_date3[i] < date_borders[j + 1]){
      birdsurveys_filtered$survey_year[i] = survey_years[j]
    }
  }
}

# creating variable for season of date
winter = list(c(1,2,12))
spring = list(c(3:5))
summer = list(c(6:8))
fall = list(c(9:11))
season_borders = c(winter,spring,summer,fall)
seasons <- c("Winter","Spring","Summer","Fall")
for (i in 1:nrow(birdsurveys_filtered)){
  for (j in 1:length(season_borders)){
    if (month(birdsurveys_filtered$obs_date3[i]) %in% season_borders[[j]]){
      birdsurveys_filtered$season[i] = seasons[j]
    }
  }
}

# joining aoc checklist with bird survey data and organizing variables
joined <- inner_join(birdsurveys_filtered,nacc_filtered,by = c("Species" = "common_name"))
joined <- joined %>% select(Year,obs_date3,survey_year,season,
                            everything(),
                            -Observation.Date,-obs_date2)

# 2021 hibernacula camera observations dataset
hibernaculapath <- here("data","hibernacula_camera_trapping_sp_list.csv")
hibernacula <- read_csv(hibernaculapath)

```

```{r,include = F}

#Notes from FHJ 2025-09-02:

# check out vegan package
#https://www.rpubs.com/an-bui/vegan-cheat-sheet

#also check out "Hill Numbers" for "effective number of species": https://esajournals.onlinelibrary.wiley.com/doi/10.1890/13-0133.1

#check out this book section:
#https://clauswilke.com/dataviz/color-pitfalls.html! 

# Response variables other than Shannon based on ebird categories:
# Shannon (or exponentiated Shannon) for species or for families
# species richness
# count for particular groups or species

#TODO what are the top 5 terrestrial insectivores with the most detections (sum of count)?

### completed
#TODO- read in using file path, not URL; check here documentation
#suggest using read_csv() rather than read.csv
#TODO join aos_checklist (NACC_list_species_2024_65th.csv) by common name, in order to analyze data by family or order
#TODO- create properly formatted date column, using lubridate functions
#TODO- create a column for "survey year"
#TODO- start saving most relevant graphs to their own files


#demo of ggsave... 
#fig_gen_type_count

#ggsave(filename = paste0("fig_general_type_count_",
#                         format(Sys.Date(), "%Y-%m-%d"),
#                         ".pdf"),
#       fig_gen_type_count,
#       width = 190,
#       height = 155,
#       units = "mm")

```

```{r}

# plot of species counts for hibernacula substrate based on most recent .csv, hibernacula_camera_trapping_sp_list.csv

hibernacula$`Common Name` <- factor(hibernacula$`Common Name`,
                                       levels = hibernacula$`Common Name`)
hibernacula <- hibernacula %>% arrange(Detections)
cthibernacula2021 <- hibernacula %>% 
  ggplot(aes(y = `Common Name`,x = Detections))+
  geom_col(fill = "mediumpurple",alpha = 0.75,show.legend = F)+
  ggtitle("2021 Camera Trapping Hibernacula Observations")+
  theme_light()+
  theme(plot.title = element_text(hjust = 0.5))

# top 5 species utilizing hibernacula:
# 1. Western Meadowlark
# 2. American Crow
# 3. Killdeer
# 4. Burrowing Owl
# 5. Canada Goose

#ggsave(filename = paste0("Camera_Trapping_Hibernacula_Composition_2021_",
#                         format(Sys.Date(),"%Y-%m-%d"),".pdf"),
#       cthibernacula2021,width = 200,height = 140,units = "mm")

plot(cthibernacula2021)

```

```{r}

# plot of spcies counts for hibernacula substrate using bird survey data

mbshibernacula <- joined %>% filter(Substrate == "Habitat Feature - Hibernacula") %>%
  ggplot(aes(y = Species,x = Count)) +
  geom_col(fill = "mediumpurple",alpha = 0.75,show.legend = F) +
  ggtitle("Hibernacula Species Composition by Bird Survey Year") +
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5)) +
  facet_wrap(~ survey_year)

# only ten total species observed for hibernacula
# slight drop off of usage from 2017-2018 to 2022-2023 - 5 species down to 1
# overlapping species from camera trapping data:
# 1. Western Meadowlark
# 2. American Crow
# 3. Burrowing Owl
# 4. Lark Sparrow
# 5. American Pipit
# does Bush Wren = Wren?

# surprised that there were so few detections for hibernacula, so manually verifying by restricting dataframe below - verified correct

# joined_hibernacula <- joined %>% filter(survey_year == "2020-2021" & Substrate == "Habitat Feature - Hibernacula")
# bshibernacula <- birdsurveys %>% filter(Year == 2020 & Substrate == "Habitat Feature - Hibernacula")

#ggsave(filename = paste0("Monthly_Bird_Survey_Hibernacula_Composition_",
#                         format(Sys.Date(),"%Y-%m-%d"),".pdf"),
#       mbshibernacula,width = 200,height = 140,units = "mm")

plot(mbshibernacula)

```

```{r,warning = F}

totals <- joined %>% group_by(survey_year,General.Type) %>% summarise(total_count = sum(Count))

totals %>% ggplot(aes(x = survey_year,y = total_count,fill = General.Type)) +
  geom_col(show.legend = F) +
  labs(x = "Survey Year",y = "Count",
       title = "Observation of General Types per Survey Year Across All Substrates") +
  facet_wrap(~ General.Type,scales = "free_y") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust = 0.5),
        plot.title = element_text(hjust = 0.5))

```

```{r,warning = F}

# number of observed species per survey year

total_species <- joined %>% group_by(survey_year,Species) %>% summarise(total_count = sum(Count))

# dataframe for count of unique species per survey year

richness <- data.frame(survey_year = unique(joined$survey_year),num_species = NA*6)
richness <- richness %>% arrange(survey_year)

for(i in 1:length(unique(total_species$survey_year))){
  temp <- total_species %>% filter(survey_year == unique(total_species$survey_year)[i])
  richness$num_species[i] <- length(unique(temp$Species))
}

richness %>% ggplot(aes(x = survey_year,y = num_species)) +
  geom_col(alpha = 0.9,fill = "seagreen3") +
  labs(x = "Survey Year",y = "Number of Species",
       title = "Total Number of Observed Species per Survey Year") +
  theme_light() +
  theme(plot.title = element_text(hjust = 0.45))

```

```{r}

# plot of count vs season by species for hibernacula substrate, visualizing which seasons relevant species appear
# would like to be able to include survey year in visualization but am not sure how

joined %>% filter(Substrate == "Habitat Feature - Hibernacula") %>% 
  ggplot(aes(y = Count,x = season)) +
  geom_col(fill = "darkorange",alpha = 0.75,show.legend = F) +
  labs(x = "Season",title = "Count of Hibernacula Species by Season") +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90,hjust = 1,vjust = 0.5),
        plot.title = element_text(hjust = 0.5)) +
  facet_wrap(~ Species)

```

