---
title: "Initial markdown"
author: "Matt Vinh"
date: "2025-08-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(colorRamps)
library(SciViews)
library(here)
```

```{r}

#TODO- read in using file path, not URL; check here documentation
#suggest using read_csv() rather than read.csv

#TODO- create properly formatted date column, using lubridate functions
#TODO- create a column for "survey year"

birdsurveys <- read.csv("https://raw.githubusercontent.com/ccber-restoration/ncos-bird-surveys/refs/heads/main/data/aggregated/dryad_2017-2023/doi_10_5061_dryad_bvq83bkhz__v20240617/NCOS_Monthly_Bird_Surveys_2017-2023.csv") %>% 
  #create column for date
  mutate(survey_date = parse_date_time(Observation.Date, "%y%m%d"))


summary(birdsurveys) # checking for data errors
# Count has 6 na's
# slough water elevation has 2703 na's
# all variables appear to have correct data type
# no extreme outliers for numeric data



```

```{r,warning = F}

# determining the number of observations per year
# all years have similar numbers of observations (mean ~ 1827) except for 2017, which only has ~400

yearrange <- unique(birdsurveys$Year)
obsperyear <- data.frame(year = yearrange,count = NA*7)

for(i in 1:7){obsperyear$count[i] <- length(which(birdsurveys$Year == yearrange[i]))}

obsperyearno2017 <- obsperyear %>% filter(count > 500)
mean(obsperyearno2017$count) # mean number of observations per year excluding 2017

# visualizing the distribution of bird count per year
# appears to be identical for every year?

birdsurveys$Year <- as.factor(birdsurveys$Year)

ggplot(data = birdsurveys,aes(x = Year,y = Count,fill = Year))+
  geom_boxplot(alpha = 0.9,outliers = F)+
  geom_jitter(alpha = 0.1,color = "grey")+
  ylim(c(0,5))

```

```{r}

# determining number of survey dates per year
# does each individual observation date signify an individual survey, or are there sometimes multiple surveys per date?

length(unique(birdsurveys$Observation.Date)) # 885 total surveys across 2017-2023

# number of unique observation dates per year
# 2021 and 2022 have totals in the 100s, but the other 5 years have only a handful of unique observation dates - seems incorrect

#surveys_per_year <- data.frame(year = yearrange,count = NA*length(yearrange))
#for(i in 1:7){
#  tempdf <- birdsurveys %>% filter(Year == yearrange[i])
#  surveys_per_year$count[i] <- length(unique(tempdf$Observation.Date))
#}

# manual verification of information determined by previous data frame
# determined that high number of total unique observation dates is result of reporting time of day in addition to date

testdf <- birdsurveys %>% filter(Year == 2021)
unique(testdf$Observation.Date)

# removing time of day from observation date variable in new data frame
# correct determination of the number of observation dates, or unique surveys, per year

birdsurv_justdates <- birdsurveys
birdsurv_justdates$Observation.Date <- substr(birdsurv_justdates$Observation.Date,1,10)
surveys_per_year_correct <- data.frame(year = yearrange,count = NA*length(yearrange))
for(i in 1:7){
  tempdf <- birdsurv_justdates %>% filter(Year == yearrange[i])
  surveys_per_year_correct$count[i] <- length(unique(tempdf$Observation.Date))
}

```

```{r}

length(unique(birdsurveys$Species)) # 169 different species

length(unique(birdsurveys$General.Type)) # 13 different general types

# visualization of counts of the different general types
# terrestrial insectivores have highest count by far
# cormorants and kingfishers have lowest counts - most specific general type?
# hard to tell colors apart

# TODO- check out this book section : https://clauswilke.com/dataviz/color-pitfalls.html! 

ggplot(data = birdsurveys,aes(x = General.Type,fill = General.Type))+
  geom_bar(alpha = 0.9)+
  theme(axis.title.x = element_blank(),axis.text.x = element_blank(),axis.ticks.x = element_blank(),
        legend.title = element_text(face = "bold"))+
  labs(y = "Count",fill = "General Type")

# TODO what are the top 5 terrestrial insectivores with the most detections (sum of count)?

```

```{r,warning = F}

# analyzing terrestrial insects by substrate

tinsect <- birdsurveys %>% filter(General.Type == "Insectivores - Terrestrial")

#unique(tinsect$Substrate)
#which(tinsect$Substrate == "")

tinsect_substrate <- birdsurveys %>% filter(General.Type == "Insectivores - Terrestrial" &
                                              Substrate != "")

# pie chart of substrate type proportion
# four most common substrates, each <= 25%: bare ground and the three vegetation types

numsubs <- length(unique(tinsect_substrate$Substrate))
col <- primary.colors(numsubs) # primary colors easier to distinguish

ggplot(data = tinsect_substrate,aes(x = "",y = Count,fill = Substrate))+
  geom_bar(stat = "identity")+
  coord_polar(theta = "y")+
  scale_fill_manual(values = col)+
  theme_void()

# per survey visualization of terrestrial insect observation count per top 5 most inhabited substrate

top5 <- c("Bare ground","Fence","Vegetation - Herbaceous","Vegetation - Shrub","Vegetation - Tree")

tinsect_substrate %>% filter(Substrate == top5 & Year != 2017) %>% 
  ggplot(aes(x = Substrate,y = Count,size = Count,color = Substrate))+
  geom_point(alpha = 0.8)+
  facet_wrap(~ Year)+
  theme(axis.title.x = element_blank(),axis.text.x = element_blank(),axis.ticks.x = element_blank(),
        legend.title = element_text(face = "bold"))

# visualization of terrestrial insect count per top 5 substrate distributions

tinsect_substrate %>% filter(Substrate == top5 & Year != 2017) %>% 
  ggplot(aes(x = Substrate,y = Count,size = Count,fill = Substrate,color = Substrate))+
  geom_violin(alpha = 0.8)+
  facet_wrap(~ Year)+
  theme(axis.title.x = element_blank(),axis.text.x = element_blank(),axis.ticks.x = element_blank(),
        legend.title = element_text(face = "bold"))

# 2017 excluded because of lower total observations

```

```{r}

# substrate analysis

#length(unique(birdsurveys$Substrate) 
# baseline 24 substrates - remove "", "<Null>", combine the two other's
# modification should result in 21 substrates

submod <- birdsurveys %>% filter(Substrate != "" & Substrate != "<Null>")
submod$Substrate[submod$Substrate == "Other (Enter in Observation Notes)"] <- "Other"

num_all_sub <- length(unique(submod$Substrate))
col2 <- primary.colors(num_all_sub)

# pie chart of all substrate types

ggplot(data = submod,aes(x = "",y = Count,fill = Substrate))+
  geom_bar(stat = "identity")+
  coord_polar(theta = "y")+
  scale_fill_manual(values = col2)+
  theme_void()

# vegetation - tree substrate general species type analysis per year

submod %>% filter(Substrate == "Vegetation - Tree" & Year != 2017) %>% 
  ggplot(aes(x = General.Type,fill = General.Type))+
  geom_bar(alpha = 0.8)+
  facet_wrap(~ Year)+
  theme_light()+
  theme(axis.text.x = element_blank(),axis.ticks.x = element_blank(),legend.title = 
          element_text(face = "bold"))+
  labs(y = "Count",x = "General Type",fill = "General Type Key")

```

$$
H = - \sum_{i=1}^{S} p_i \ln(p_i)
\newline Shannon \, \, Diversity \, \, Index
$$ $$
E_H = H / ln(S)
\newline Shannon \, \, Evenness \, \, Index
$$

```{r}

# shannon diversity and evenness indices analysis

unique(submod$Count) # NA values present
submod <- submod[!is.na(submod$Count),] # remove NA's

yearrange <- unique(birdsurveys$Year)
yearrange <- sort(yearrange)

a <- submod %>% filter(Year == 2017) %>% select(c(Year,eBird.Group,Count,Substrate))
b <- submod %>% filter(Year == 2018) %>% select(c(Year,eBird.Group,Count,Substrate))
c <- submod %>% filter(Year == 2019) %>% select(c(Year,eBird.Group,Count,Substrate))
d <- submod %>% filter(Year == 2020) %>% select(c(Year,eBird.Group,Count,Substrate))
e <- submod %>% filter(Year == 2021) %>% select(c(Year,eBird.Group,Count,Substrate))
f <- submod %>% filter(Year == 2022) %>% select(c(Year,eBird.Group,Count,Substrate))
g <- submod %>% filter(Year == 2023) %>% select(c(Year,eBird.Group,Count,Substrate))
dflist <- list(shannon2017 = a,shannon2018 = b,shannon2019 = c,shannon2020 = d,shannon2021 = e,
               shannon2022 = f,shannon2023 = g)

compiled_dflist <- list()
sub_totals_per_year <- list()
joined <- list()
shannon <- list()

for(i in 1:7){
  compiled_dflist[[i]] <- dflist[[i]] %>% group_by(Substrate,eBird.Group) %>% 
    summarise(count = sum(Count))
  names(compiled_dflist) <- paste0("compiled_",yearrange[i])
  compiled_dflist[[i]]$year <- rep(yearrange[i],nrow(compiled_dflist[[i]]))
  sub_totals_per_year[[i]] <- compiled_dflist[[i]] %>% group_by(Substrate) %>% 
    summarise(total = sum(count))
  names(sub_totals_per_year) <- paste0("sub_totals_",yearrange[i])
  joined[[i]] <- compiled_dflist[[i]] %>% inner_join(sub_totals_per_year[[i]],by = "Substrate")
  joined[[i]] <- joined[[i]] %>% mutate(proportion = count / total)
  shannon[[i]] <- joined[[i]] %>% group_by(Substrate) %>% 
    mutate(diversity = -1 * sum(proportion * ln(proportion))) %>% 
    mutate(evenness = diversity / ln())
}

dflist[[1]] %>% group_by(Substrate) %>% summarise(total = sum(ount))

```
