---
title: "MV_2025-12-16"
output: html_document
---

```{r setup}

library(here)
library(tidyverse)
library(grid)
library(patchwork)
library(knitr)

datapath <- here("data","aggregated","MV_updated_aggregated.rds")
data <- readRDS(datapath)

```

```{r species richness}

richness <- data %>% group_by(survey_year,substrate) %>% 
  mutate(richness = length(unique(species)))
richness <- richness %>% select(c(survey_year,substrate,richness)) %>% 
  distinct(survey_year,substrate,richness) %>% mutate(grouping = case_when(
    grepl("Vegetation",substrate) ~ 1,
    substrate == "Air" ~ 2,
    substrate == "Bare ground" ~ 2,
    substrate == "Unknown" ~ 2,
    grepl("Water",substrate) ~ 3,
    substrate == "Mud" ~ 3,
    substrate == "Bridge" ~ 4,
    substrate == "Building" ~ 4,
    substrate == "Fence" ~ 4,
    substrate == "Other" ~ 4,
    grepl("Habitat",substrate) ~ 5))

colors <- palette.colors(16,"Alphabet")

richness1 <- ggplot(richness %>% filter(grouping == 1),
                    aes(x = survey_year,y = richness,group = substrate,
                                 color = substrate)) + geom_line(alpha = 0.85) + 
  theme_light() + labs(x = NULL,y = NULL,color = "Substrate") + 
  scale_color_manual(values = colors[1:3]) + 
  scale_x_continuous(breaks = seq(1,8,1))

richness2 <- ggplot(richness %>% filter(grouping == 2),
                    aes(x = survey_year,y = richness,group = substrate,
                                 color = substrate)) + geom_line(alpha = 0.85) + 
  theme_light() + labs(x = NULL,y = NULL,color = "Substrate") + 
  scale_color_manual(values = colors[4:6]) + 
  scale_x_continuous(breaks = seq(1,8,1))

richness3 <- ggplot(richness %>% filter(grouping == 3),
                    aes(x = survey_year,y = richness,group = substrate,
                                 color = substrate)) + geom_line(alpha = 0.85) + 
  theme_light() + labs(x = NULL,y = "Species Richness",color = "Substrate") + 
  scale_color_manual(values = colors[7:9]) + 
  scale_x_continuous(breaks = seq(1,8,1))

richness4 <- ggplot(richness %>% filter(grouping == 4),
                    aes(x = survey_year,y = richness,group = substrate,
                                 color = substrate)) + geom_line(alpha = 0.85) + 
  theme_light() + labs(x = "Survey Year",y = "Species Richness",color = "Substrate") + 
  scale_color_manual(values = colors[10:13]) + 
  scale_x_continuous(breaks = seq(1,8,1))

richness5 <- ggplot(richness %>% filter(grouping == 5),
                    aes(x = survey_year,y = richness,group = substrate,
                                 color = substrate)) + geom_line(alpha = 0.85) + 
  theme_light() + labs(x = "Survey Year",y = NULL,color = "Substrate") + 
  scale_color_manual(values = colors[14:16]) + 
  scale_x_continuous(breaks = seq(1,8,1))

(richness1 + richness2) / (richness3 + richness4) / (richness5 + plot_spacer()) + 
  plot_annotation(title = "Species Richness by Substrate per Survey Year",
                  theme = theme(plot.title = element_text(hjust = 0.5))) + 
  plot_layout(axis_titles = "collect")

```

```{r breeding period}

breed <- data %>% filter(substrate != "Air/Flyover" & substrate != "Other" & 
                           substrate != "Rock" & substrate != "telephone wire" & 
                           substrate != "Vernal Pool") %>% mutate(period = case_when(
  month(observation_date) %in% c(4:7) ~ "breeding",
  month(observation_date) %in% c(8:11) ~ "summer_fall",
  month(observation_date) %in% c(1:3,12) ~ "winter_spring")) %>% 
    group_by(substrate,survey_year,period) %>% mutate(mean_count = mean(count)) %>% 
  distinct(survey_year,period,substrate,mean_count)
levels(breed$substrate)[levels(breed$substrate) == "Habitat Feature - Hibernacula"] <- "Hibernacula"
levels(breed$substrate)[levels(breed$substrate) == "Habitat Feature - Log"] <- "Log"
levels(breed$substrate)[levels(breed$substrate) == "Habitat Feature - Snag"] <- "Snag"
levels(breed$substrate)[levels(breed$substrate) == "Vegetation - Herbaceous"] <- "Herbaceous"
levels(breed$substrate)[levels(breed$substrate) == "Vegetation - Shrub"] <- "Shrub"
levels(breed$substrate)[levels(breed$substrate) == "Vegetation - Tree"] <- "Tree"

ggplot(breed,aes(x = survey_year,y = mean_count,color = period)) + 
  geom_line() + facet_wrap(~ substrate,scale = "free_y")

# habitat feature - snag and air substrates have higher average counts during
# hypothetical breeding period than other thirds of the survey year
# year thirds defined as four-month blocks preceding and following april-july breeding
# air is less relevant?

```

```{r all species utilizing snag substrate}

snag_species <- unique(data$species[data$substrate == "Habitat Feature - Snag"])
frame <- data.frame(snag_species = snag_species)
kable(frame)

```

```{r guild abundance,message = F}

# by year

guild_abundance_year <- data %>% group_by(survey_year,general_type) %>% 
  summarise(abundance = sum(count)) %>% distinct(survey_year,general_type,abundance)

ggplot(guild_abundance_year,aes(x = survey_year,y = abundance)) +  
  geom_line() + facet_wrap(~ general_type,scale = "free_y") + theme_light() + 
  labs(title = "Guild Species Abundance by Survey Year",x = "Survey Year",y = "Species Abundance") + 
  theme(plot.title = element_text(hjust = 0.5)) + scale_x_continuous(breaks = seq(1,8,by = 1))

# by season

guild_abundance_season <- data %>% group_by(season,general_type) %>% 
  summarise(average_abundance = mean(count)) %>% distinct(season,general_type,average_abundance)

ggplot(guild_abundance_season,aes(x = season,y = average_abundance,fill = season)) + 
  geom_col(alpha = 0.8) + facet_wrap(~ general_type,scale = "free_y") + theme_light() + 
  labs(title = "Average Guild Species Abundance by Season",x = "Season",
       y = "Average Species Abundance",fill = "Season") + 
  theme(plot.title = element_text(hjust = 0.5),axis.text.x = element_text(angle = 90))

# by year and season composite

season_map <- c(Fall = 0,Winter = 0.25,Spring = 0.5,Summer = 0.75)
data$year_and_season <- data$survey_year + season_map[data$season]

guild_abundance_year_and_season <- data %>% group_by(year_and_season,general_type) %>% 
  summarise(abundance = sum(count)) %>% distinct(year_and_season,general_type,abundance)

text1 <- textGrob("x-axis ticks = survey year + season, defined by the following map:\nfall = 0,winter = 0.25, spring = 0.5, summer = 0.75")

gabundance1 <- ggplot(guild_abundance_year_and_season,aes(x = year_and_season,y = abundance)) + 
  geom_line() + facet_wrap(~ general_type,scale = "free_y") + theme_light() + 
  labs(title = "Guild Species Abundance by Season per Survey Year",x = "Survey Year + Season",
       y = "Species Abundance") + theme(plot.title = element_text(hjust = 0.5)) + 
  scale_x_continuous(breaks = seq(1,9,by = 1))

gabundance1 + inset_element(text1,left = 0.35,right = 0.9,bottom = 0,top = 0.2)

```

```{r guild richness,message = F}

# by year

guild_richness_year <- data %>% group_by(survey_year,general_type) %>% 
  mutate(richness = length(unique(species))) %>% distinct(survey_year,general_type,richness)

ggplot(guild_richness_year,aes(x = survey_year,y = richness)) + 
  geom_line() + facet_wrap(~ general_type,scale = "free_y") + theme_light() + 
  labs(title = "Guild Richness by Survey Year",x = "Survey Year",y = "Species Richness") + 
  theme(plot.title = element_text(hjust = 0.5)) + scale_x_continuous(breaks = seq(1,8,by = 1))
  

# by season

guild_richness_season <- data %>% group_by(survey_year,season,general_type) %>% 
  mutate(richness = length(unique(species))) %>% distinct(survey_year,season,general_type,richness) %>% 
  group_by(season,general_type) %>% summarise(average_richness = mean(richness)) %>% 
  distinct(season,general_type,average_richness)

ggplot(guild_richness_season,aes(x = season,y = average_richness,fill = season)) + 
  geom_col(alpha = 0.8) + facet_wrap(~ general_type,scale = "free_y") + theme_light() + 
  labs(title = "Average Guild Species Richness by Season",x = "Season",
       y = "Average Species Richness",fill = "Season") + 
  theme(plot.title = element_text(hjust = 0.5),axis.text.x = element_text(angle = 90))

# cormorants and kingfishers only record one species

# by year and season composite

guild_richness_year_and_season <- data %>% group_by(year_and_season,general_type) %>% 
  mutate(richness = length(unique(species))) %>% distinct(year_and_season,general_type,richness)

grichness1 <- ggplot(guild_richness_year_and_season,aes(x = year_and_season,y = richness)) + 
  geom_line() + facet_wrap(~ general_type,scale = "free_y") + theme_light() + 
  labs(title = "Guild Species Richness by Season per Survey Year",x = "Survey Year + Season",
       y = "Species Richness") + 
  theme(plot.title = element_text(hjust = 0.5)) + scale_x_continuous(breaks = seq(1,9,by = 1))

grichness1 + inset_element(text1,left = 0.35,right = 0.9,bottom = 0,top = 0.2)

```

