---
title: "MV_2025-11-07_2"
output: html_document
---

# relative proportion per habitat by year all on one graph, to compare to each other
# figure captions

# patchwork package?

# nmds for max abundance per species per year
# nmds for mean abundance per species per year

```{r,include = F}

library(tidyverse)
library(here)
library(vegan)
library(ggrepel)

MVaggregatedpath <- here("data","aggregated","MV_aggregated.csv")
aggregated <- read_csv(MVaggregatedpath)

```

```{r}

# recreating NMDS by season with updated aggregated data (new "Unknown" substrate)

community1 <- xtabs(Count ~ Observation_Date + Species,data = aggregated)
community1 <- as.matrix(unclass(community1))
nmds1 <- metaMDS(community1,autotransform = F,distance = "bray",engine = "monoMDS",k = 2,weakties = T,model = "global",maxit = 300,try = 40,trymax = 100,trace = F)

print(nmds1) # stress = 0.201 - much higher than 0.07

stressplot(nmds1,lwd = 3)

season <- aggregated %>% distinct(Observation_Date,Season)
season$Observation_Date <- as.character(season$Observation_Date)
nmds1_odscores <- as.data.frame(scores(nmds1)$sites) %>% 
  rownames_to_column(var = "Observation_Date") %>% 
  left_join(season)
season_centroid <- nmds1_odscores %>% group_by(Season) %>% summarise(
  axis1 = mean(NMDS1),
  axis2 = mean(NMDS2)) %>% ungroup()
season_shape <- nmds1_odscores %>% group_by(Season) %>% slice(chull(NMDS1,NMDS2))

nmdsfigure <- ggplot() + geom_point(data = nmds1_odscores,
                                    aes(x = NMDS1,y = NMDS2,color = Season),size = 1.5) + 
  geom_point(data = season_centroid,aes(x = axis1,y = axis2,color = Season),size = 6,shape = 17) + 
  geom_polygon(data = season_shape,aes(x = NMDS1,y = NMDS2,fill = Season,group = Season),alpha = 0.25) +
  annotate("text",x = 0,y = 1.25,label = paste("2D stress =",round(nmds1$stress,3))) + 
  theme_light() + xlim(c(-1,1)) + ylim(c(-1.5,1.5)) +
  labs(title = "NMDS of Species by Season") + theme(plot.title = element_text(hjust = 0.5))
plot(nmdsfigure) # plot reflects higher stress - less overlap

#ggsave(filename = paste0("Season_NMDS_Updated",format(Sys.Date(),"%y-%m-%d"),".pdf"),
#       nmdsfigure,width = 200,height = 140,units = "mm")

```

```{r}

# dataframe of total count per species per year
total_counts <- aggregated %>% 
  group_by(Species,Survey_Year) %>% 
  summarise(total_count = sum(Count))

community2 <- xtabs(total_count ~ Survey_Year + Species,data = total_counts)
community2 <- as.matrix(unclass(community2))

nmds2 <- metaMDS(community2,autotransform = F,distance = "bray",engine = "monoMDS",k = 2,weakties = T,model = "global",maxit = 300,try = 40,trymax = 100,trace = F)

print(nmds2)
stressplot(nmds2)

nmds2_odscores <- as.data.frame(scores(nmds2)$sites) %>% 
  rownames_to_column(var = "Survey_Year")

years_centroid <- nmds2_odscores %>% group_by(Survey_Year) %>% summarise(
  axis1 = mean(NMDS1),
  axis2 = mean(NMDS2)) %>% ungroup()

years_shape <- nmds2_odscores %>% group_by(Survey_Year) %>% slice(chull(NMDS1,NMDS2))

ggplot() + geom_point(data = nmds2_odscores,aes(x = NMDS1,y = NMDS2,color = Survey_Year),size = 1.5) + 
  geom_point(data = years_centroid,aes(x = axis1,y = axis2,color = Survey_Year),size = 6,shape = 17) + 
  geom_polygon(data = years_shape,aes(x = NMDS1,y = NMDS2,fill = Survey_Year,group = Survey_Year),
               alpha = 0.25) +
  annotate("text",x = 0,y = 1.25,label = paste("2D stress =",round(nmds2$stress,3))) + 
  theme_light() + 
  labs(title = "NMDS of Species by Survey Year") + theme(plot.title = element_text(hjust = 0.5))

```

```{r}

# corrected NMDS of maximum count per species per year

year_max <- aggregated %>% group_by(Species,Survey_Year) %>% 
  summarise(max_count = max(Count))

community3 <- xtabs(max_count ~ Survey_Year + Species,data = year_max)
community3 <- as.matrix(unclass(community3))

nmds3 <- metaMDS(community3,autotransform = F,distance = "bray",engine = "monoMDS",k = 2,weakties = T,model = "global",maxit = 300,try = 40,trymax = 100,trace = F)

print(nmds3)
stressplot(nmds3)

nmds3_scores <- as.data.frame(scores(nmds3)$sites) %>% 
  rownames_to_column(var = "Survey_Year")

years_centroid <- nmds3_scores %>% group_by(Survey_Year) %>% summarise(
  axis1 = mean(NMDS1),
  axis2 = mean(NMDS2)) %>% ungroup()

years_shape <- nmds3_scores %>% group_by(Survey_Year) %>% slice(chull(NMDS1,NMDS2))

ggplot() + geom_point(data = nmds3_scores,aes(x = NMDS1,y = NMDS2,color = Survey_Year),size = 1.5) + 
  geom_point(data = years_centroid,aes(x = axis1,y = axis2,color = Survey_Year),size = 6,shape = 17) + 
  geom_polygon(data = years_shape,aes(x = NMDS1,y = NMDS2,fill = Survey_Year,group = Survey_Year),
               alpha = 0.25) +
  #annotate("text",x = 0,y = 1.25,label = paste("2D stress =",round(nmds3$stress,3))) + 
  theme_light() + 
  labs(title = "NMDS of Maximum Survey Count per Species per Year") + 
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}

survey_max <- aggregated %>% group_by(Species,Observation_Date) %>% 
  summarise(max_count = max(Count))

community4 <- xtabs(max_count ~ Observation_Date + Species,data = survey_max)
community4 <- as.matrix(unclass(community4))

nmds4 <- metaMDS(community4,autotransform = F,distance = "bray",engine = "monoMDS",k = 2,weakties = T,model = "global",maxit = 300,try = 40,trymax = 100,trace = F)

print(nmds4)
stressplot(nmds4)

years <- aggregated %>% distinct(Observation_Date,Survey_Year)
years$Observation_Date <- as.character(years$Observation_Date)

nmds4_scores <- as.data.frame(scores(nmds4)$sites) %>% 
  rownames_to_column(var = "Observation_Date") %>% 
  left_join(years)

years_centroid <- nmds4_scores %>% group_by(Survey_Year) %>% summarise(
  axis1 = mean(NMDS1),
  axis2 = mean(NMDS2)) %>% ungroup()

years_shape <- nmds4_scores %>% group_by(Survey_Year) %>% slice(chull(NMDS1,NMDS2))

ggplot() + geom_point(data = nmds4_scores,aes(x = NMDS1,y = NMDS2,color = Survey_Year),size = 1.5) + 
  geom_point(data = years_centroid,aes(x = axis1,y = axis2,color = Survey_Year),size = 6,shape = 17) + 
  geom_polygon(data = years_shape,aes(x = NMDS1,y = NMDS2,fill = Survey_Year,group = Survey_Year),
               alpha = 0.25) +
  #annotate("text",x = 0,y = 1.25,label = paste("2D stress =",round(nmds3$stress,3))) + 
  theme_light() + 
  labs(title = "NMDS of Maximum Survey Count per Species per Survey") + 
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}

year_mean <- aggregated %>% group_by(Species,Survey_Year) %>% 
  summarise(mean_count = mean(Count))

community5 <- xtabs(mean_count ~ Survey_Year + Species,data = year_mean)
community5 <- as.matrix(unclass(community5))

nmds5 <- metaMDS(community5,autotransform = F,distance = "bray",engine = "monoMDS",k = 2,weakties = T,model = "global",maxit = 300,try = 40,trymax = 100,trace = F)

print(nmds5)
stressplot(nmds5)

nmds5_scores <- as.data.frame(scores(nmds5)$sites) %>% 
  rownames_to_column(var = "Survey_Year")
  
years_centroid <- nmds5_scores %>% group_by(Survey_Year) %>% summarise(
  axis1 = mean(NMDS1),
  axis2 = mean(NMDS2)) %>% ungroup()

years_shape <- nmds5_scores %>% group_by(Survey_Year) %>% slice(chull(NMDS1,NMDS2))

ggplot() + geom_point(data = nmds5_scores,aes(x = NMDS1,y = NMDS2,color = Survey_Year),size = 1.5) + 
  geom_point(data = years_centroid,aes(x = axis1,y = axis2,color = Survey_Year),size = 6,shape = 17) + 
  geom_polygon(data = years_shape,aes(x = NMDS1,y = NMDS2,fill = Survey_Year,group = Survey_Year),
               alpha = 0.25) +
  #annotate("text",x = 0,y = 1.25,label = paste("2D stress =",round(nmds3$stress,3))) + 
  theme_light() + 
  labs(title = "NMDS of Maximum Survey Count per Species per Survey") + 
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}

relative_proportions <- aggregated %>% group_by(Survey_Year,Substrate) %>%
  summarize(substrate_count = sum(Count)) %>% 
  mutate(total = sum(substrate_count)) %>% 
  mutate(proportion = substrate_count / total)

chosen <- relative_proportions %>% filter(Substrate != "Air/Flyover" & Substrate != "Flyover" & Substrate != "Rock" & Substrate != "telephone wire" & Substrate != "Vernal Pool")
# removes 12 rows, 8 flyover rows and 1 of each of the others

chosen_end <- chosen %>% group_by(Substrate) %>% slice_max(Survey_Year)

ggplot(chosen,aes(x = Survey_Year,y = proportion,group = Substrate,color = Substrate)) + 
  geom_line(alpha = 0.85) + theme_light() + 
  geom_text(data = chosen_end,aes(label = Substrate),nudge_x = 0.3,hjust = 0) + 
  labs(title = "Overlay of Substrate Observation Proportions over Time",
       x = "Survey Year",y = "Proportion") + 
  theme(plot.title = element_text(hjust = 0.5),legend.position = "none") + 
  scale_x_continuous(breaks = seq(1,11,by = 1)) + xlim(c(1,11))

```


```{r}

df <- tibble(
  name = c("Alice", "Alice", "Bob", "Bob"),
  measurement = c("height", "weight", "height", "weight"),
  value = c(65, 120, 70, 150)
)

wide_df <- df %>% 
  pivot_wider(
    names_from = measurement,
    values_from = value
  )

df
wide_df



```

